// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CollaboratorUsecase is an autogenerated mock type for the CollaboratorUsecase type
type CollaboratorUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, collaborator
func (_m *CollaboratorUsecase) Create(ctx context.Context, collaborator *domain.Collaborator) (*domain.Collaborator, error) {
	ret := _m.Called(ctx, collaborator)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Collaborator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Collaborator) (*domain.Collaborator, error)); ok {
		return rf(ctx, collaborator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Collaborator) *domain.Collaborator); ok {
		r0 = rf(ctx, collaborator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Collaborator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Collaborator) error); ok {
		r1 = rf(ctx, collaborator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CollaboratorUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *CollaboratorUsecase) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Collaborator, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Collaborator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Collaborator, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Collaborator); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Collaborator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *CollaboratorUsecase) GetById(ctx context.Context, id uuid.UUID) (*domain.Collaborator, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Collaborator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Collaborator, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Collaborator); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Collaborator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, eventID, search, page, pageSize
func (_m *CollaboratorUsecase) ListPaged(ctx context.Context, eventID uuid.UUID, search string, page int32, pageSize int32) ([]domain.Collaborator, int64, error) {
	ret := _m.Called(ctx, eventID, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Collaborator
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]domain.Collaborator, int64, error)); ok {
		return rf(ctx, eventID, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []domain.Collaborator); ok {
		r0 = rf(ctx, eventID, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Collaborator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) int64); ok {
		r1 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r2 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, collaborator
func (_m *CollaboratorUsecase) Update(ctx context.Context, id uuid.UUID, collaborator *domain.UpdateCollaborator) (*domain.Collaborator, error) {
	ret := _m.Called(ctx, id, collaborator)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Collaborator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateCollaborator) (*domain.Collaborator, error)); ok {
		return rf(ctx, id, collaborator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateCollaborator) *domain.Collaborator); ok {
		r0 = rf(ctx, id, collaborator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Collaborator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateCollaborator) error); ok {
		r1 = rf(ctx, id, collaborator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCollaboratorUsecase creates a new instance of CollaboratorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCollaboratorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CollaboratorUsecase {
	mock := &CollaboratorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
