// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DeveloperUsecase is an autogenerated mock type for the DeveloperUsecase type
type DeveloperUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, developer
func (_m *DeveloperUsecase) Create(ctx context.Context, developer *domain.Developer) (*domain.Developer, error) {
	ret := _m.Called(ctx, developer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Developer) (*domain.Developer, error)); ok {
		return rf(ctx, developer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Developer) *domain.Developer); ok {
		r0 = rf(ctx, developer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Developer) error); ok {
		r1 = rf(ctx, developer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DeveloperUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *DeveloperUsecase) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Developer, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Developer, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Developer); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *DeveloperUsecase) GetById(ctx context.Context, id uuid.UUID) (*domain.Developer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Developer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Developer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, eventID, search, page, pageSize
func (_m *DeveloperUsecase) ListPaged(ctx context.Context, eventID uuid.UUID, search string, page int32, pageSize int32) ([]domain.Developer, int64, error) {
	ret := _m.Called(ctx, eventID, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Developer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]domain.Developer, int64, error)); ok {
		return rf(ctx, eventID, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []domain.Developer); ok {
		r0 = rf(ctx, eventID, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) int64); ok {
		r1 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r2 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, upDev
func (_m *DeveloperUsecase) Update(ctx context.Context, id uuid.UUID, upDev *domain.UpdateDeveloper) (*domain.Developer, error) {
	ret := _m.Called(ctx, id, upDev)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Developer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateDeveloper) (*domain.Developer, error)); ok {
		return rf(ctx, id, upDev)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateDeveloper) *domain.Developer); ok {
		r0 = rf(ctx, id, upDev)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Developer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateDeveloper) error); ok {
		r1 = rf(ctx, id, upDev)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeveloperUsecase creates a new instance of DeveloperUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeveloperUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeveloperUsecase {
	mock := &DeveloperUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
