// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// EventUsecase is an autogenerated mock type for the EventUsecase type
type EventUsecase struct {
	mock.Mock
}

// CreateEvent provides a mock function with given fields: ctx, event
func (_m *EventUsecase) CreateEvent(ctx context.Context, event *domain.Event) (*domain.Event, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for CreateEvent")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) (*domain.Event, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Event) *domain.Event); ok {
		r0 = rf(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Event) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteEvent provides a mock function with given fields: ctx, id
func (_m *EventUsecase) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveEvents provides a mock function with given fields: ctx
func (_m *EventUsecase) GetActiveEvents(ctx context.Context) ([]domain.Event, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveEvents")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *EventUsecase) GetByID(ctx context.Context, id uuid.UUID) (*domain.Event, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Event, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Event); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventBySlug provides a mock function with given fields: ctx, slug
func (_m *EventUsecase) GetEventBySlug(ctx context.Context, slug string) (*domain.Event, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetEventBySlug")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Event, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Event); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEvents provides a mock function with given fields: ctx
func (_m *EventUsecase) GetEvents(ctx context.Context) ([]domain.Event, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 []domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Event, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEventsPaged provides a mock function with given fields: ctx, search, page, pageSize, orderBy
func (_m *EventUsecase) GetEventsPaged(ctx context.Context, search string, page int32, pageSize int32, orderBy string) ([]domain.Event, int64, error) {
	ret := _m.Called(ctx, search, page, pageSize, orderBy)

	if len(ret) == 0 {
		panic("no return value specified for GetEventsPaged")
	}

	var r0 []domain.Event
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, string) ([]domain.Event, int64, error)); ok {
		return rf(ctx, search, page, pageSize, orderBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32, string) []domain.Event); ok {
		r0 = rf(ctx, search, page, pageSize, orderBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32, string) int64); ok {
		r1 = rf(ctx, search, page, pageSize, orderBy)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, int32, string) error); ok {
		r2 = rf(ctx, search, page, pageSize, orderBy)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateEvent provides a mock function with given fields: ctx, id, evUpdate
func (_m *EventUsecase) UpdateEvent(ctx context.Context, id uuid.UUID, evUpdate *domain.UpdateEvent) (*domain.Event, error) {
	ret := _m.Called(ctx, id, evUpdate)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEvent")
	}

	var r0 *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateEvent) (*domain.Event, error)); ok {
		return rf(ctx, id, evUpdate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateEvent) *domain.Event); ok {
		r0 = rf(ctx, id, evUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateEvent) error); ok {
		r1 = rf(ctx, id, evUpdate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventUsecase creates a new instance of EventUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventUsecase {
	mock := &EventUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
