// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrganizerRepository is an autogenerated mock type for the OrganizerRepository type
type OrganizerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, organizer
func (_m *OrganizerRepository) Create(ctx context.Context, organizer *domain.Organizer) (*domain.Organizer, error) {
	ret := _m.Called(ctx, organizer)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Organizer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Organizer) (*domain.Organizer, error)); ok {
		return rf(ctx, organizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Organizer) *domain.Organizer); ok {
		r0 = rf(ctx, organizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Organizer) error); ok {
		r1 = rf(ctx, organizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *OrganizerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *OrganizerRepository) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Organizer, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Organizer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Organizer, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Organizer); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *OrganizerRepository) GetById(ctx context.Context, id uuid.UUID) (*domain.Organizer, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Organizer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Organizer, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Organizer); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPersonAndEvent provides a mock function with given fields: ctx, personID, eventID
func (_m *OrganizerRepository) GetByPersonAndEvent(ctx context.Context, personID uuid.UUID, eventID uuid.UUID) (uuid.UUID, error) {
	ret := _m.Called(ctx, personID, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetByPersonAndEvent")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (uuid.UUID, error)); ok {
		return rf(ctx, personID, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) uuid.UUID); ok {
		r0 = rf(ctx, personID, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, personID, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, eventID, search, page, pageSize
func (_m *OrganizerRepository) ListPaged(ctx context.Context, eventID uuid.UUID, search string, page int32, pageSize int32) ([]domain.Organizer, int64, error) {
	ret := _m.Called(ctx, eventID, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Organizer
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]domain.Organizer, int64, error)); ok {
		return rf(ctx, eventID, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []domain.Organizer); ok {
		r0 = rf(ctx, eventID, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) int64); ok {
		r1 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r2 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, organizer
func (_m *OrganizerRepository) Update(ctx context.Context, organizer *domain.Organizer) (*domain.Organizer, error) {
	ret := _m.Called(ctx, organizer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Organizer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Organizer) (*domain.Organizer, error)); ok {
		return rf(ctx, organizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Organizer) *domain.Organizer); ok {
		r0 = rf(ctx, organizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Organizer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Organizer) error); ok {
		r1 = rf(ctx, organizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrganizerRepository creates a new instance of OrganizerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizerRepository {
	mock := &OrganizerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
