// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"
	dtos "devfest/internal/infrastructure/api/dtos"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PersonUsecase is an autogenerated mock type for the PersonUsecase type
type PersonUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, dto
func (_m *PersonUsecase) Create(ctx context.Context, dto dtos.CreatePersonDTO) (*domain.Person, error) {
	ret := _m.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dtos.CreatePersonDTO) (*domain.Person, error)); ok {
		return rf(ctx, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.CreatePersonDTO) *domain.Person); ok {
		r0 = rf(ctx, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.CreatePersonDTO) error); ok {
		r1 = rf(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PersonUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *PersonUsecase) GetAll(ctx context.Context) ([]domain.Person, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *PersonUsecase) GetByEmail(ctx context.Context, email *string) (*domain.Person, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *domain.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *string) (*domain.Person, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *string) *domain.Person); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PersonUsecase) GetByID(ctx context.Context, id uuid.UUID) (*domain.Person, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Person); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, search, page, pageSize
func (_m *PersonUsecase) ListPaged(ctx context.Context, search string, page int32, pageSize int32) ([]domain.Person, int64, error) {
	ret := _m.Called(ctx, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Person
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) ([]domain.Person, int64, error)); ok {
		return rf(ctx, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int32, int32) []domain.Person); ok {
		r0 = rf(ctx, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int32, int32) int64); ok {
		r1 = rf(ctx, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int32, int32) error); ok {
		r2 = rf(ctx, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, dto
func (_m *PersonUsecase) Update(ctx context.Context, id uuid.UUID, dto dtos.UpdatePersonDTO) (*domain.Person, error) {
	ret := _m.Called(ctx, id, dto)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.UpdatePersonDTO) (*domain.Person, error)); ok {
		return rf(ctx, id, dto)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dtos.UpdatePersonDTO) *domain.Person); ok {
		r0 = rf(ctx, id, dto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dtos.UpdatePersonDTO) error); ok {
		r1 = rf(ctx, id, dto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPersonUsecase creates a new instance of PersonUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonUsecase {
	mock := &PersonUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
