// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SchedulerRepository is an autogenerated mock type for the SchedulerRepository type
type SchedulerRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, scheduler
func (_m *SchedulerRepository) Create(ctx context.Context, scheduler *domain.Scheduler) (*domain.Scheduler, error) {
	ret := _m.Called(ctx, scheduler)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Scheduler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scheduler) (*domain.Scheduler, error)); ok {
		return rf(ctx, scheduler)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scheduler) *domain.Scheduler); ok {
		r0 = rf(ctx, scheduler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scheduler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Scheduler) error); ok {
		r1 = rf(ctx, scheduler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SchedulerRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllByTrack provides a mock function with given fields: ctx, trackID
func (_m *SchedulerRepository) GetAllByTrack(ctx context.Context, trackID uuid.UUID) ([]domain.Scheduler, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetAllByTrack")
	}

	var r0 []domain.Scheduler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Scheduler, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Scheduler); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Scheduler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *SchedulerRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Scheduler, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Scheduler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Scheduler, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Scheduler); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scheduler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, scheduler
func (_m *SchedulerRepository) Update(ctx context.Context, scheduler *domain.Scheduler) (*domain.Scheduler, error) {
	ret := _m.Called(ctx, scheduler)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Scheduler
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scheduler) (*domain.Scheduler, error)); ok {
		return rf(ctx, scheduler)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Scheduler) *domain.Scheduler); ok {
		r0 = rf(ctx, scheduler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Scheduler)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Scheduler) error); ok {
		r1 = rf(ctx, scheduler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSchedulerRepository creates a new instance of SchedulerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerRepository {
	mock := &SchedulerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
