// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SpeakerUsecase is an autogenerated mock type for the SpeakerUsecase type
type SpeakerUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, speaker
func (_m *SpeakerUsecase) Create(ctx context.Context, speaker *domain.Speaker) (*domain.Speaker, error) {
	ret := _m.Called(ctx, speaker)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Speaker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Speaker) (*domain.Speaker, error)); ok {
		return rf(ctx, speaker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Speaker) *domain.Speaker); ok {
		r0 = rf(ctx, speaker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Speaker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Speaker) error); ok {
		r1 = rf(ctx, speaker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SpeakerUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *SpeakerUsecase) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Speaker, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Speaker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Speaker, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Speaker); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Speaker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *SpeakerUsecase) GetById(ctx context.Context, id uuid.UUID) (*domain.Speaker, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Speaker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Speaker, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Speaker); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Speaker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, eventID, search, page, pageSize
func (_m *SpeakerUsecase) ListPaged(ctx context.Context, eventID uuid.UUID, search string, page int32, pageSize int32) ([]domain.Speaker, int64, error) {
	ret := _m.Called(ctx, eventID, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Speaker
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]domain.Speaker, int64, error)); ok {
		return rf(ctx, eventID, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []domain.Speaker); ok {
		r0 = rf(ctx, eventID, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Speaker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) int64); ok {
		r1 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r2 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, id, upSpeaker
func (_m *SpeakerUsecase) Update(ctx context.Context, id uuid.UUID, upSpeaker *domain.UpdateSpeaker) (*domain.Speaker, error) {
	ret := _m.Called(ctx, id, upSpeaker)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Speaker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateSpeaker) (*domain.Speaker, error)); ok {
		return rf(ctx, id, upSpeaker)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateSpeaker) *domain.Speaker); ok {
		r0 = rf(ctx, id, upSpeaker)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Speaker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateSpeaker) error); ok {
		r1 = rf(ctx, id, upSpeaker)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSpeakerUsecase creates a new instance of SpeakerUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpeakerUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpeakerUsecase {
	mock := &SpeakerUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
