// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SponsorRepository is an autogenerated mock type for the SponsorRepository type
type SponsorRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, sponsor
func (_m *SponsorRepository) Create(ctx context.Context, sponsor *domain.Sponsor) (*domain.Sponsor, error) {
	ret := _m.Called(ctx, sponsor)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Sponsor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Sponsor) (*domain.Sponsor, error)); ok {
		return rf(ctx, sponsor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Sponsor) *domain.Sponsor); ok {
		r0 = rf(ctx, sponsor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sponsor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Sponsor) error); ok {
		r1 = rf(ctx, sponsor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *SponsorRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *SponsorRepository) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Sponsor, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Sponsor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Sponsor, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Sponsor); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Sponsor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *SponsorRepository) GetById(ctx context.Context, id uuid.UUID) (*domain.Sponsor, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Sponsor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Sponsor, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Sponsor); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sponsor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPaged provides a mock function with given fields: ctx, eventID, search, page, pageSize
func (_m *SponsorRepository) ListPaged(ctx context.Context, eventID uuid.UUID, search string, page int32, pageSize int32) ([]domain.Sponsor, int64, error) {
	ret := _m.Called(ctx, eventID, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListPaged")
	}

	var r0 []domain.Sponsor
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) ([]domain.Sponsor, int64, error)); ok {
		return rf(ctx, eventID, search, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, int32, int32) []domain.Sponsor); ok {
		r0 = rf(ctx, eventID, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Sponsor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, int32, int32) int64); ok {
		r1 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, int32, int32) error); ok {
		r2 = rf(ctx, eventID, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, sponsor
func (_m *SponsorRepository) Update(ctx context.Context, sponsor *domain.Sponsor) (*domain.Sponsor, error) {
	ret := _m.Called(ctx, sponsor)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Sponsor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Sponsor) (*domain.Sponsor, error)); ok {
		return rf(ctx, sponsor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Sponsor) *domain.Sponsor); ok {
		r0 = rf(ctx, sponsor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Sponsor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Sponsor) error); ok {
		r1 = rf(ctx, sponsor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSponsorRepository creates a new instance of SponsorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSponsorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SponsorRepository {
	mock := &SponsorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
