// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TalkRepository is an autogenerated mock type for the TalkRepository type
type TalkRepository struct {
	mock.Mock
}

// AddSpeaker provides a mock function with given fields: ctx, speaker
func (_m *TalkRepository) AddSpeaker(ctx context.Context, speaker *domain.TalkSpeaker) error {
	ret := _m.Called(ctx, speaker)

	if len(ret) == 0 {
		panic("no return value specified for AddSpeaker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TalkSpeaker) error); ok {
		r0 = rf(ctx, speaker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, talk
func (_m *TalkRepository) Create(ctx context.Context, talk *domain.Talk) (*domain.Talk, error) {
	ret := _m.Called(ctx, talk)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Talk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Talk) (*domain.Talk, error)); ok {
		return rf(ctx, talk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Talk) *domain.Talk); ok {
		r0 = rf(ctx, talk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Talk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Talk) error); ok {
		r1 = rf(ctx, talk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TalkRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *TalkRepository) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Talk, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Talk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Talk, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Talk); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Talk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *TalkRepository) GetById(ctx context.Context, id uuid.UUID) (*domain.Talk, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Talk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Talk, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Talk); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Talk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveSpeaker provides a mock function with given fields: ctx, speaker
func (_m *TalkRepository) RemoveSpeaker(ctx context.Context, speaker *domain.TalkSpeaker) error {
	ret := _m.Called(ctx, speaker)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSpeaker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TalkSpeaker) error); ok {
		r0 = rf(ctx, speaker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, talk
func (_m *TalkRepository) Update(ctx context.Context, talk *domain.Talk) (*domain.Talk, error) {
	ret := _m.Called(ctx, talk)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Talk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Talk) (*domain.Talk, error)); ok {
		return rf(ctx, talk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Talk) *domain.Talk); ok {
		r0 = rf(ctx, talk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Talk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Talk) error); ok {
		r1 = rf(ctx, talk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTalkRepository creates a new instance of TalkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTalkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TalkRepository {
	mock := &TalkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
