// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "devfest/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TrackRepository is an autogenerated mock type for the TrackRepository type
type TrackRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, track
func (_m *TrackRepository) Create(ctx context.Context, track *domain.Track) (*domain.Track, error) {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Track) (*domain.Track, error)); ok {
		return rf(ctx, track)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Track) *domain.Track); ok {
		r0 = rf(ctx, track)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Track) error); ok {
		r1 = rf(ctx, track)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, trackID
func (_m *TrackRepository) Delete(ctx context.Context, trackID uuid.UUID) error {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, trackID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, eventID
func (_m *TrackRepository) GetAll(ctx context.Context, eventID uuid.UUID) ([]domain.Track, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Track, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Track); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, trackID
func (_m *TrackRepository) GetById(ctx context.Context, trackID uuid.UUID) (*domain.Track, error) {
	ret := _m.Called(ctx, trackID)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Track, error)); ok {
		return rf(ctx, trackID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Track); ok {
		r0 = rf(ctx, trackID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, trackID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFullEventSchedule provides a mock function with given fields: ctx, eventID
func (_m *TrackRepository) GetFullEventSchedule(ctx context.Context, eventID uuid.UUID) ([]domain.FullTrackSchedule, error) {
	ret := _m.Called(ctx, eventID)

	if len(ret) == 0 {
		panic("no return value specified for GetFullEventSchedule")
	}

	var r0 []domain.FullTrackSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.FullTrackSchedule, error)); ok {
		return rf(ctx, eventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.FullTrackSchedule); ok {
		r0 = rf(ctx, eventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FullTrackSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, eventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, track
func (_m *TrackRepository) Update(ctx context.Context, track *domain.Track) (*domain.Track, error) {
	ret := _m.Called(ctx, track)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Track) (*domain.Track, error)); ok {
		return rf(ctx, track)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Track) *domain.Track); ok {
		r0 = rf(ctx, track)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Track) error); ok {
		r1 = rf(ctx, track)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTrackRepository creates a new instance of TrackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackRepository {
	mock := &TrackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
