openapi: 3.0.3
info:
  title: Community Event API
  description: API for Community Events Management.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development Server

components:

  # --- SECURITY SCHEMES ---

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  # --- PARAMETERS ---

  parameters:
    IdPath:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
    PageParam:
      name: page
      in: query
      schema:
        type: integer
        default: 1
    PageSizeParam:
      name: pageSize
      in: query
      schema:
        type: integer
        default: 10
    SearchParam:
      name: search
      in: query
      schema:
        type: string

  # --- RESPONSES ---

  responses:
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
    ConflictError:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AppError'
  
  # --- SCHEMAS ---

  schemas:
    # --- GENERICS ---

    Audit:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        created_by:
          type: string
          format: uuid
        updated_by:
          type: string
          format: uuid
    AppError:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
        code:
          type: string
        trace_id:
          type: string
    PagedMeta:
      type: object
      properties:
        total:
          type: integer
          format: int64
          example: 100
        page:
          type: integer
          format: int32
          example: 1
        pageSize:
          type: integer
          format: int32
          example: 10

    # --- EVENTS ---

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        is_active:
          type: boolean
        audit:
          $ref: '#/components/schemas/Audit'
    CreateEventDTO:
      type: object
      required:
        - name
        - slug
      properties:
        name:
          type: string
        slug:
          type: string
        is_active:
          type: boolean
    UpdateEventDTO:
      type: object
      properties:
        name:
          type: string
        slug:
          type: string
        is_active:
          type: boolean
    EventPagedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        meta:
          $ref: '#/components/schemas/PagedMeta'
    
    # --- PERSONS ---

    Person:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        avatar_url:
          type: string
        github_user:
          type: string
        linkedin_url:
          type: string
        twitter_url:
          type: string
        website_url:
          type: string
        audit:
          $ref: '#/components/schemas/Audit'
    CreatePersonDTO:
      type: object
      required:
        - first_name
        - last_name
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        avatar_url:
          type: string
        github_user:
          type: string
        linkedin_url:
          type: string
        twitter_url:
          type: string
        website_url:
          type: string
    UpdatePersonDTO:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        avatar_url:
          type: string
        github_user:
          type: string
        linkedin_url:
          type: string
        twitter_url:
          type: string
        website_url:
          type: string
    PersonPagedResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        meta:
          $ref: '#/components/schemas/PagedMeta'

# --- PATHS ---

paths:

  # --- EVENTS ---

  /api/v1/events:
    get:
      summary: Get all events
      description: Get all events
      tags:
        - Events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create an event
      description: Create an event
      tags:
        - Events
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEventDTO'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/events/{id}:
    put:
      summary: Update an event by ID
      description: Update an event by ID
      tags:
        - Events
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEventDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete an event by ID
      description: Delete an event by ID
      tags:
        - Events
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No Content
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/events/id/{id}:
    get:
      summary: Get an event by ID
      description: Get an event by ID
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/events/slug/{slug}:
    get:
      summary: Get an event by slug
      description: Get an event by slug
      tags:
        - Events
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/events/status/active:  
    get:  
      summary: Get all active events  
      description: Get all active events  
      tags:  
        - Events  
      responses:  
        '200':  
          description: OK  
          content:  
            application/json:  
              schema:  
                type: array  
                items:  
                  $ref: '#/components/schemas/Event'  
        '500':  
          $ref: '#/components/responses/InternalServerError'
  /api/v1/events/paged:
    get:
      summary: Get all events with pagination
      description: Get all events with pagination
      tags:
        - Events
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - name: order
          description: Order by
          in: query
          required: false
          schema:
            type: string
            description: Field to order by and direction (asc or desc)
            example: name_asc
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventPagedResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'
  
  # --- PERSONS ---
  
  /api/v1/persons:
    get:
      summary: Get all persons
      description: Get all persons
      tags:
        - Persons
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Create a person
      description: Create a person
      tags:
        - Persons
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePersonDTO'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/persons/{id}:
    put:
      summary: Update a person by ID
      description: Update a person by ID
      tags:
        - Persons
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePersonDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '409':
          $ref: '#/components/responses/ConflictError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      summary: Delete a person by ID
      description: Delete a person by ID
      tags:
        - Persons
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: No content
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/persons/id/{id}:
    get:
      summary: Get events for a person by ID
      description: Get events for a person by ID
      tags:
        - Persons
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/persons/email/{email}:
    get:
      summary: Get a person by email
      description: Get a person by email
      tags:
        - Persons
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/v1/persons/paged:
    get:
      summary: Get all persons with pagination
      description: Get all persons with pagination
      tags:
        - Persons
      parameters:
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/PagedResponse'
        '500':
          $ref: '#/components/responses/InternalServerError'