// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collaborators.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCollaboratorsByEvent = `-- name: CountCollaboratorsByEvent :one
SELECT COUNT(*) 
FROM collaborators c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountCollaboratorsByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountCollaboratorsByEvent(ctx context.Context, arg CountCollaboratorsByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCollaboratorsByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollaborator = `-- name: CreateCollaborator :one
INSERT INTO collaborators (
  person_id, 
  event_id, 
  area, 
  created_by, 
  updated_by
)
VALUES (
  $1, $2, $3, $4, $4
)
RETURNING id, person_id, event_id, area, created_at, updated_at, created_by, updated_by
`

type CreateCollaboratorParams struct {
	PersonID  uuid.UUID   `json:"person_id"`
	EventID   uuid.UUID   `json:"event_id"`
	Area      pgtype.Text `json:"area"`
	CreatedBy uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateCollaborator(ctx context.Context, arg CreateCollaboratorParams) (Collaborator, error) {
	row := q.db.QueryRow(ctx, createCollaborator,
		arg.PersonID,
		arg.EventID,
		arg.Area,
		arg.CreatedBy,
	)
	var i Collaborator
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Area,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteCollaborator = `-- name: DeleteCollaborator :exec
DELETE FROM collaborators 
WHERE id = $1
`

func (q *Queries) DeleteCollaborator(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollaborator, id)
	return err
}

const getCollaboratorByID = `-- name: GetCollaboratorByID :one
SELECT 
  c.id, c.person_id, c.event_id, c.area, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM collaborators c
JOIN persons p ON c.person_id = p.id
WHERE c.id = $1 LIMIT 1
`

type GetCollaboratorByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Area        pgtype.Text        `json:"area"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
}

func (q *Queries) GetCollaboratorByID(ctx context.Context, id uuid.UUID) (GetCollaboratorByIDRow, error) {
	row := q.db.QueryRow(ctx, getCollaboratorByID, id)
	var i GetCollaboratorByIDRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Area,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.TwitterUrl,
		&i.LinkedinUrl,
		&i.WebsiteUrl,
	)
	return i, err
}

const getCollaboratorByPersonAndEvent = `-- name: GetCollaboratorByPersonAndEvent :one
SELECT id FROM collaborators 
WHERE person_id = $1 AND event_id = $2
`

type GetCollaboratorByPersonAndEventParams struct {
	PersonID uuid.UUID `json:"person_id"`
	EventID  uuid.UUID `json:"event_id"`
}

func (q *Queries) GetCollaboratorByPersonAndEvent(ctx context.Context, arg GetCollaboratorByPersonAndEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCollaboratorByPersonAndEvent, arg.PersonID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCollaboratorsByEvent = `-- name: ListCollaboratorsByEvent :many
SELECT 
  c.id, c.person_id, c.event_id, c.area, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM collaborators c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1
`

type ListCollaboratorsByEventRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Area        pgtype.Text        `json:"area"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
}

func (q *Queries) ListCollaboratorsByEvent(ctx context.Context, eventID uuid.UUID) ([]ListCollaboratorsByEventRow, error) {
	rows, err := q.db.Query(ctx, listCollaboratorsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollaboratorsByEventRow
	for rows.Next() {
		var i ListCollaboratorsByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Area,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
			&i.WebsiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollaboratorsByEventPaged = `-- name: ListCollaboratorsByEventPaged :many
SELECT 
  c.id, c.person_id, c.event_id, c.area, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM collaborators c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($4, '') || '%' OR
    p.email ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY p.first_name ASC
LIMIT $2 OFFSET $3
`

type ListCollaboratorsByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

type ListCollaboratorsByEventPagedRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Area        pgtype.Text        `json:"area"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
}

func (q *Queries) ListCollaboratorsByEventPaged(ctx context.Context, arg ListCollaboratorsByEventPagedParams) ([]ListCollaboratorsByEventPagedRow, error) {
	rows, err := q.db.Query(ctx, listCollaboratorsByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollaboratorsByEventPagedRow
	for rows.Next() {
		var i ListCollaboratorsByEventPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Area,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
			&i.WebsiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollaborator = `-- name: UpdateCollaborator :one
UPDATE collaborators SET 
  area = COALESCE($3, area), 
  updated_at = NOW(), 
  updated_by = $2
WHERE id = $1 
RETURNING id, person_id, event_id, area, created_at, updated_at, created_by, updated_by
`

type UpdateCollaboratorParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy uuid.UUID   `json:"updated_by"`
	Area      pgtype.Text `json:"area"`
}

func (q *Queries) UpdateCollaborator(ctx context.Context, arg UpdateCollaboratorParams) (Collaborator, error) {
	row := q.db.QueryRow(ctx, updateCollaborator, arg.ID, arg.UpdatedBy, arg.Area)
	var i Collaborator
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Area,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
