// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: developers.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDevelopersByEvent = `-- name: CountDevelopersByEvent :one
SELECT COUNT(*) 
FROM developers d
JOIN persons p ON d.person_id = p.id
WHERE d.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountDevelopersByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountDevelopersByEvent(ctx context.Context, arg CountDevelopersByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDevelopersByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeveloper = `-- name: CreateDeveloper :one
INSERT INTO developers (
  person_id, 
  event_id, 
  role_description, 
  created_by, 
  updated_by)
VALUES (
  $1, $2, $3, $4, $4
)
RETURNING id, person_id, event_id, role_description, created_at, updated_at, created_by, updated_by
`

type CreateDeveloperParams struct {
	PersonID        uuid.UUID   `json:"person_id"`
	EventID         uuid.UUID   `json:"event_id"`
	RoleDescription pgtype.Text `json:"role_description"`
	CreatedBy       uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateDeveloper(ctx context.Context, arg CreateDeveloperParams) (Developer, error) {
	row := q.db.QueryRow(ctx, createDeveloper,
		arg.PersonID,
		arg.EventID,
		arg.RoleDescription,
		arg.CreatedBy,
	)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteDeveloper = `-- name: DeleteDeveloper :exec
DELETE FROM developers 
WHERE id = $1
`

func (q *Queries) DeleteDeveloper(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeveloper, id)
	return err
}

const getDeveloperByID = `-- name: GetDeveloperByID :one
SELECT 
  d.id, d.person_id, d.event_id, d.role_description, d.created_at, d.updated_at, d.created_by, d.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM developers d
JOIN persons p ON d.person_id = p.id
WHERE d.id = $1 LIMIT 1
`

type GetDeveloperByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl      pgtype.Text        `json:"website_url"`
}

func (q *Queries) GetDeveloperByID(ctx context.Context, id uuid.UUID) (GetDeveloperByIDRow, error) {
	row := q.db.QueryRow(ctx, getDeveloperByID, id)
	var i GetDeveloperByIDRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.TwitterUrl,
		&i.LinkedinUrl,
		&i.WebsiteUrl,
	)
	return i, err
}

const getDeveloperByPersonAndEvent = `-- name: GetDeveloperByPersonAndEvent :one
SELECT id FROM developers 
WHERE person_id = $1 AND event_id = $2
`

type GetDeveloperByPersonAndEventParams struct {
	PersonID uuid.UUID `json:"person_id"`
	EventID  uuid.UUID `json:"event_id"`
}

func (q *Queries) GetDeveloperByPersonAndEvent(ctx context.Context, arg GetDeveloperByPersonAndEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDeveloperByPersonAndEvent, arg.PersonID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listDevelopersByEvent = `-- name: ListDevelopersByEvent :many
SELECT 
  d.id, d.person_id, d.event_id, d.role_description, d.created_at, d.updated_at, d.created_by, d.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM developers d
JOIN persons p ON d.person_id = p.id
WHERE d.event_id = $1
`

type ListDevelopersByEventRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl      pgtype.Text        `json:"website_url"`
}

func (q *Queries) ListDevelopersByEvent(ctx context.Context, eventID uuid.UUID) ([]ListDevelopersByEventRow, error) {
	rows, err := q.db.Query(ctx, listDevelopersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevelopersByEventRow
	for rows.Next() {
		var i ListDevelopersByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.RoleDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
			&i.WebsiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDevelopersByEventPaged = `-- name: ListDevelopersByEventPaged :many
SELECT 
  d.id, d.person_id, d.event_id, d.role_description, d.created_at, d.updated_at, d.created_by, d.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url, p.website_url
FROM developers d
JOIN persons p ON d.person_id = p.id
WHERE d.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY p.first_name ASC
LIMIT $2 OFFSET $3
`

type ListDevelopersByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

type ListDevelopersByEventPagedRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
	WebsiteUrl      pgtype.Text        `json:"website_url"`
}

func (q *Queries) ListDevelopersByEventPaged(ctx context.Context, arg ListDevelopersByEventPagedParams) ([]ListDevelopersByEventPagedRow, error) {
	rows, err := q.db.Query(ctx, listDevelopersByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevelopersByEventPagedRow
	for rows.Next() {
		var i ListDevelopersByEventPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.RoleDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
			&i.WebsiteUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeveloper = `-- name: UpdateDeveloper :one
UPDATE developers 
SET 
  role_description = COALESCE($3, role_description), 
  updated_at = NOW(), 
  updated_by = $2
WHERE id = $1 RETURNING id, person_id, event_id, role_description, created_at, updated_at, created_by, updated_by
`

type UpdateDeveloperParams struct {
	ID              uuid.UUID   `json:"id"`
	UpdatedBy       uuid.UUID   `json:"updated_by"`
	RoleDescription pgtype.Text `json:"role_description"`
}

func (q *Queries) UpdateDeveloper(ctx context.Context, arg UpdateDeveloperParams) (Developer, error) {
	row := q.db.QueryRow(ctx, updateDeveloper, arg.ID, arg.UpdatedBy, arg.RoleDescription)
	var i Developer
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
