// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
WHERE 
    (name ILIKE '%' || $1::text || '%' OR $1::text = '')
`

func (q *Queries) CountEvents(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    name, 
    slug, 
    is_active, 
    created_by
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, name, slug, is_active, created_at, updated_at, created_by, updated_by
`

type CreateEventParams struct {
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	IsActive  pgtype.Bool `json:"is_active"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Name,
		arg.Slug,
		arg.IsActive,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one

SELECT id, name, slug, is_active, created_at, updated_at, created_by, updated_by FROM events
WHERE id = $1 LIMIT 1
`

// queries/events.sql
func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, name, slug, is_active, created_at, updated_at, created_by, updated_by FROM events
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listActiveEvents = `-- name: ListActiveEvents :many
SELECT id, name, slug, is_active, created_at, updated_at, created_by, updated_by FROM events
WHERE is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListActiveEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listActiveEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, slug, is_active, created_at, updated_at, created_by, updated_by FROM events
ORDER BY created_at DESC
`

func (q *Queries) ListEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsPaged = `-- name: ListEventsPaged :many
SELECT id, name, slug, is_active, created_at, updated_at, created_by, updated_by FROM events
WHERE 
    (name ILIKE '%' || $1::text || '%' OR $1::text = '')
ORDER BY 
    CASE WHEN $4::text = 'name_asc' THEN name END ASC,
    CASE WHEN $4::text = 'name_desc' THEN name END DESC,
    CASE WHEN $4::text = 'created_at_asc' THEN created_at END ASC,
    CASE WHEN $4::text = 'created_at_desc' THEN created_at END DESC
LIMIT $2 OFFSET $3
`

type ListEventsPagedParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
	Column4 string `json:"column_4"`
}

func (q *Queries) ListEventsPaged(ctx context.Context, arg ListEventsPagedParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsPaged,
		arg.Column1,
		arg.Limit,
		arg.Offset,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET name = $2,
    slug = $3,
    is_active = $4,
    updated_by = $5
WHERE id = $1
RETURNING id, name, slug, is_active, created_at, updated_at, created_by, updated_by
`

type UpdateEventParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	IsActive  pgtype.Bool `json:"is_active"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.IsActive,
		arg.UpdatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
