// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Collaborator struct {
	ID        uuid.UUID          `json:"id"`
	PersonID  uuid.UUID          `json:"person_id"`
	EventID   uuid.UUID          `json:"event_id"`
	Area      pgtype.Text        `json:"area"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UpdatedBy uuid.UUID          `json:"updated_by"`
}

type Developer struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
}

type Event struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UpdatedBy uuid.UUID          `json:"updated_by"`
}

type Organizer struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	Company         pgtype.Text        `json:"company"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
}

type Person struct {
	ID          uuid.UUID          `json:"id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	WebsiteUrl  pgtype.Text        `json:"website_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
}

type Scheduler struct {
	ID        uuid.UUID          `json:"id"`
	TrackID   uuid.UUID          `json:"track_id"`
	TalkID    pgtype.UUID        `json:"talk_id"`
	StartTime pgtype.Time        `json:"start_time"`
	EndTime   pgtype.Time        `json:"end_time"`
	Duration  pgtype.Interval    `json:"duration"`
	Room      pgtype.Text        `json:"room"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Speaker struct {
	ID        uuid.UUID          `json:"id"`
	PersonID  uuid.UUID          `json:"person_id"`
	EventID   uuid.UUID          `json:"event_id"`
	Bio       pgtype.Text        `json:"bio"`
	Company   pgtype.Text        `json:"company"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UpdatedBy uuid.UUID          `json:"updated_by"`
}

type Sponsor struct {
	ID            uuid.UUID          `json:"id"`
	EventID       uuid.UUID          `json:"event_id"`
	Name          string             `json:"name"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	WebsiteUrl    pgtype.Text        `json:"website_url"`
	Tier          pgtype.Text        `json:"tier"`
	OrderPriority pgtype.Int4        `json:"order_priority"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     uuid.UUID          `json:"created_by"`
	UpdatedBy     uuid.UUID          `json:"updated_by"`
}

type Talk struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
}

type TalkSpeaker struct {
	TalkID    uuid.UUID          `json:"talk_id"`
	SpeakerID uuid.UUID          `json:"speaker_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
}

type Track struct {
	ID        uuid.UUID          `json:"id"`
	EventID   uuid.UUID          `json:"event_id"`
	Name      string             `json:"name"`
	EventDate pgtype.Date        `json:"event_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedBy uuid.UUID          `json:"created_by"`
	UpdatedBy uuid.UUID          `json:"updated_by"`
}
