// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizers.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizersByEvent = `-- name: CountOrganizersByEvent :one
SELECT COUNT(*) 
FROM organizers c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountOrganizersByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountOrganizersByEvent(ctx context.Context, arg CountOrganizersByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizersByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizer = `-- name: CreateOrganizer :one
INSERT INTO organizers (
  person_id, 
  event_id, 
  company,
  role_description,
  created_by, 
  updated_by
)
VALUES (
  $1, $2, $3, $4, $5, $5
)
RETURNING id, person_id, event_id, company, role_description, created_at, updated_at, created_by, updated_by
`

type CreateOrganizerParams struct {
	PersonID        uuid.UUID   `json:"person_id"`
	EventID         uuid.UUID   `json:"event_id"`
	Company         pgtype.Text `json:"company"`
	RoleDescription pgtype.Text `json:"role_description"`
	CreatedBy       uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateOrganizer(ctx context.Context, arg CreateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, createOrganizer,
		arg.PersonID,
		arg.EventID,
		arg.Company,
		arg.RoleDescription,
		arg.CreatedBy,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Company,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteOrganizer = `-- name: DeleteOrganizer :exec
DELETE FROM organizers 
WHERE id = $1
`

func (q *Queries) DeleteOrganizer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizer, id)
	return err
}

const getOrganizerByID = `-- name: GetOrganizerByID :one
SELECT 
  c.id, c.person_id, c.event_id, c.company, c.role_description, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM organizers c
JOIN persons p ON c.person_id = p.id
WHERE c.id = $1 LIMIT 1
`

type GetOrganizerByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	Company         pgtype.Text        `json:"company"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) GetOrganizerByID(ctx context.Context, id uuid.UUID) (GetOrganizerByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizerByID, id)
	var i GetOrganizerByIDRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Company,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.TwitterUrl,
		&i.LinkedinUrl,
	)
	return i, err
}

const getOrganizerByPersonAndEvent = `-- name: GetOrganizerByPersonAndEvent :one
SELECT id FROM organizers 
WHERE person_id = $1 AND event_id = $2
`

type GetOrganizerByPersonAndEventParams struct {
	PersonID uuid.UUID `json:"person_id"`
	EventID  uuid.UUID `json:"event_id"`
}

func (q *Queries) GetOrganizerByPersonAndEvent(ctx context.Context, arg GetOrganizerByPersonAndEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getOrganizerByPersonAndEvent, arg.PersonID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listOrganizersByEvent = `-- name: ListOrganizersByEvent :many
SELECT 
  c.id, c.person_id, c.event_id, c.company, c.role_description, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM organizers c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1
`

type ListOrganizersByEventRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	Company         pgtype.Text        `json:"company"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) ListOrganizersByEvent(ctx context.Context, eventID uuid.UUID) ([]ListOrganizersByEventRow, error) {
	rows, err := q.db.Query(ctx, listOrganizersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizersByEventRow
	for rows.Next() {
		var i ListOrganizersByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Company,
			&i.RoleDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizersByEventPaged = `-- name: ListOrganizersByEventPaged :many
SELECT 
  c.id, c.person_id, c.event_id, c.company, c.role_description, c.created_at, c.updated_at, c.created_by, c.updated_by, 
  p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM organizers c
JOIN persons p ON c.person_id = p.id
WHERE c.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($4, '') || '%' OR
    p.email ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY p.first_name ASC
LIMIT $2 OFFSET $3
`

type ListOrganizersByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

type ListOrganizersByEventPagedRow struct {
	ID              uuid.UUID          `json:"id"`
	PersonID        uuid.UUID          `json:"person_id"`
	EventID         uuid.UUID          `json:"event_id"`
	Company         pgtype.Text        `json:"company"`
	RoleDescription pgtype.Text        `json:"role_description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	UpdatedBy       uuid.UUID          `json:"updated_by"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	Email           pgtype.Text        `json:"email"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	GithubUser      pgtype.Text        `json:"github_user"`
	TwitterUrl      pgtype.Text        `json:"twitter_url"`
	LinkedinUrl     pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) ListOrganizersByEventPaged(ctx context.Context, arg ListOrganizersByEventPagedParams) ([]ListOrganizersByEventPagedRow, error) {
	rows, err := q.db.Query(ctx, listOrganizersByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizersByEventPagedRow
	for rows.Next() {
		var i ListOrganizersByEventPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Company,
			&i.RoleDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizer = `-- name: UpdateOrganizer :one
UPDATE organizers SET 
  company = COALESCE($3, company),
  role_description = COALESCE($4, role_description),
  updated_at = NOW(), 
  updated_by = $2
WHERE id = $1 
RETURNING id, person_id, event_id, company, role_description, created_at, updated_at, created_by, updated_by
`

type UpdateOrganizerParams struct {
	ID              uuid.UUID   `json:"id"`
	UpdatedBy       uuid.UUID   `json:"updated_by"`
	Company         pgtype.Text `json:"company"`
	RoleDescription pgtype.Text `json:"role_description"`
}

func (q *Queries) UpdateOrganizer(ctx context.Context, arg UpdateOrganizerParams) (Organizer, error) {
	row := q.db.QueryRow(ctx, updateOrganizer,
		arg.ID,
		arg.UpdatedBy,
		arg.Company,
		arg.RoleDescription,
	)
	var i Organizer
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Company,
		&i.RoleDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
