// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: person.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPersons = `-- name: CountPersons :one
SELECT count(*) FROM persons
WHERE 
    (first_name ILIKE '%' || $1::text || '%' OR 
     last_name ILIKE '%' || $1::text || '%' OR 
     email ILIKE '%' || $1::text || '%')
`

func (q *Queries) CountPersons(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countPersons, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons (
    first_name, last_name, email, avatar_url, 
    github_user, linkedin_url, twitter_url, website_url,
    created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $9
)
RETURNING id, first_name, last_name, email, avatar_url, github_user, linkedin_url, twitter_url, website_url, created_at, updated_at, created_by, updated_by
`

type CreatePersonParams struct {
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       pgtype.Text `json:"email"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	GithubUser  pgtype.Text `json:"github_user"`
	LinkedinUrl pgtype.Text `json:"linkedin_url"`
	TwitterUrl  pgtype.Text `json:"twitter_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AvatarUrl,
		arg.GithubUser,
		arg.LinkedinUrl,
		arg.TwitterUrl,
		arg.WebsiteUrl,
		arg.CreatedBy,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.LinkedinUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deletePerson = `-- name: DeletePerson :exec
DELETE FROM persons
WHERE id = $1
`

func (q *Queries) DeletePerson(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePerson, id)
	return err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, first_name, last_name, email, avatar_url, github_user, linkedin_url, twitter_url, website_url, created_at, updated_at, created_by, updated_by FROM persons
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email pgtype.Text) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.LinkedinUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getPersonByID = `-- name: GetPersonByID :one
SELECT id, first_name, last_name, email, avatar_url, github_user, linkedin_url, twitter_url, website_url, created_at, updated_at, created_by, updated_by FROM persons
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPersonByID(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.LinkedinUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listPersonsPaged = `-- name: ListPersonsPaged :many
SELECT id, first_name, last_name, email, avatar_url, github_user, linkedin_url, twitter_url, website_url, created_at, updated_at, created_by, updated_by FROM persons
WHERE 
    (first_name ILIKE '%' || $3::text || '%' OR 
     last_name ILIKE '%' || $3::text || '%' OR 
     email ILIKE '%' || $3::text || '%')
ORDER BY last_name ASC, first_name ASC
LIMIT $1 OFFSET $2
`

type ListPersonsPagedParams struct {
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
	Search string `json:"search"`
}

// Usamos un listado con búsqueda básica por nombre/email y paginación
func (q *Queries) ListPersonsPaged(ctx context.Context, arg ListPersonsPagedParams) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPersonsPaged, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.LinkedinUrl,
			&i.TwitterUrl,
			&i.WebsiteUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE persons
SET 
    first_name = $2,
    last_name = $3,
    email = $4,
    avatar_url = $5,
    github_user = $6,
    linkedin_url = $7,
    twitter_url = $8,
    website_url = $9,
    updated_by = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, first_name, last_name, email, avatar_url, github_user, linkedin_url, twitter_url, website_url, created_at, updated_at, created_by, updated_by
`

type UpdatePersonParams struct {
	ID          uuid.UUID   `json:"id"`
	FirstName   string      `json:"first_name"`
	LastName    string      `json:"last_name"`
	Email       pgtype.Text `json:"email"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	GithubUser  pgtype.Text `json:"github_user"`
	LinkedinUrl pgtype.Text `json:"linkedin_url"`
	TwitterUrl  pgtype.Text `json:"twitter_url"`
	WebsiteUrl  pgtype.Text `json:"website_url"`
	UpdatedBy   uuid.UUID   `json:"updated_by"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.AvatarUrl,
		arg.GithubUser,
		arg.LinkedinUrl,
		arg.TwitterUrl,
		arg.WebsiteUrl,
		arg.UpdatedBy,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.LinkedinUrl,
		&i.TwitterUrl,
		&i.WebsiteUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
