// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountEvents(ctx context.Context, dollar_1 string) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEvent(ctx context.Context, id uuid.UUID) error
	// queries/events.sql
	GetEventByID(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventBySlug(ctx context.Context, slug string) (Event, error)
	ListActiveEvents(ctx context.Context) ([]Event, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsPaged(ctx context.Context, arg ListEventsPagedParams) ([]Event, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
}

var _ Querier = (*Queries)(nil)
