// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduler.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScheduleEntry = `-- name: CreateScheduleEntry :one
INSERT INTO scheduler (
    track_id,
    talk_id,
    start_time,
    end_time,
    room
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, track_id, talk_id, start_time, end_time, duration, room, updated_at
`

type CreateScheduleEntryParams struct {
	TrackID   uuid.UUID   `json:"track_id"`
	TalkID    pgtype.UUID `json:"talk_id"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Room      pgtype.Text `json:"room"`
}

func (q *Queries) CreateScheduleEntry(ctx context.Context, arg CreateScheduleEntryParams) (Scheduler, error) {
	row := q.db.QueryRow(ctx, createScheduleEntry,
		arg.TrackID,
		arg.TalkID,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
	)
	var i Scheduler
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.TalkID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Room,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleEntry = `-- name: DeleteScheduleEntry :exec
DELETE FROM scheduler
WHERE id = $1
`

func (q *Queries) DeleteScheduleEntry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScheduleEntry, id)
	return err
}

const getScheduleEntryByID = `-- name: GetScheduleEntryByID :one
SELECT 
    sch.id, sch.track_id, sch.talk_id, sch.start_time, sch.end_time, sch.duration, sch.room, sch.updated_at, 
    t.title as talk_title,
    p.first_name as speaker_name,
    p.last_name as speaker_last_name,
    tr.name as track_name,
    tr.event_date
FROM scheduler sch
LEFT JOIN talks t ON sch.talk_id = t.id
LEFT JOIN speakers s ON t.speaker_id = s.id
LEFT JOIN persons p ON s.person_id = p.id
JOIN tracks tr ON sch.track_id = tr.id
WHERE sch.id = $1 LIMIT 1
`

type GetScheduleEntryByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	TrackID         uuid.UUID          `json:"track_id"`
	TalkID          pgtype.UUID        `json:"talk_id"`
	StartTime       pgtype.Time        `json:"start_time"`
	EndTime         pgtype.Time        `json:"end_time"`
	Duration        pgtype.Interval    `json:"duration"`
	Room            pgtype.Text        `json:"room"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TalkTitle       pgtype.Text        `json:"talk_title"`
	SpeakerName     pgtype.Text        `json:"speaker_name"`
	SpeakerLastName pgtype.Text        `json:"speaker_last_name"`
	TrackName       string             `json:"track_name"`
	EventDate       pgtype.Date        `json:"event_date"`
}

func (q *Queries) GetScheduleEntryByID(ctx context.Context, id uuid.UUID) (GetScheduleEntryByIDRow, error) {
	row := q.db.QueryRow(ctx, getScheduleEntryByID, id)
	var i GetScheduleEntryByIDRow
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.TalkID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Room,
		&i.UpdatedAt,
		&i.TalkTitle,
		&i.SpeakerName,
		&i.SpeakerLastName,
		&i.TrackName,
		&i.EventDate,
	)
	return i, err
}

const listFullEventSchedule = `-- name: ListFullEventSchedule :many
SELECT 
    sch.id, sch.track_id, sch.talk_id, sch.start_time, sch.end_time, sch.duration, sch.room, sch.updated_at, 
    tr.name as track_name,
    tr.event_date,
    t.title as talk_title,
    p.first_name as speaker_name,
    p.last_name as speaker_last_name
FROM scheduler sch
JOIN tracks tr ON sch.track_id = tr.id
LEFT JOIN talks t ON sch.talk_id = t.id
LEFT JOIN speakers s ON t.speaker_id = s.id
LEFT JOIN persons p ON s.person_id = p.id
WHERE tr.event_id = $1
ORDER BY tr.event_date ASC, sch.start_time ASC
`

type ListFullEventScheduleRow struct {
	ID              uuid.UUID          `json:"id"`
	TrackID         uuid.UUID          `json:"track_id"`
	TalkID          pgtype.UUID        `json:"talk_id"`
	StartTime       pgtype.Time        `json:"start_time"`
	EndTime         pgtype.Time        `json:"end_time"`
	Duration        pgtype.Interval    `json:"duration"`
	Room            pgtype.Text        `json:"room"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TrackName       string             `json:"track_name"`
	EventDate       pgtype.Date        `json:"event_date"`
	TalkTitle       pgtype.Text        `json:"talk_title"`
	SpeakerName     pgtype.Text        `json:"speaker_name"`
	SpeakerLastName pgtype.Text        `json:"speaker_last_name"`
}

func (q *Queries) ListFullEventSchedule(ctx context.Context, eventID uuid.UUID) ([]ListFullEventScheduleRow, error) {
	rows, err := q.db.Query(ctx, listFullEventSchedule, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFullEventScheduleRow
	for rows.Next() {
		var i ListFullEventScheduleRow
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.TalkID,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Room,
			&i.UpdatedAt,
			&i.TrackName,
			&i.EventDate,
			&i.TalkTitle,
			&i.SpeakerName,
			&i.SpeakerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleByTrack = `-- name: ListScheduleByTrack :many
SELECT 
    sch.id, sch.track_id, sch.talk_id, sch.start_time, sch.end_time, sch.duration, sch.room, sch.updated_at, 
    t.title as talk_title,
    p.first_name as speaker_name,
    p.last_name as speaker_last_name
FROM scheduler sch
LEFT JOIN talks t ON sch.talk_id = t.id
LEFT JOIN speakers s ON t.speaker_id = s.id
LEFT JOIN persons p ON s.person_id = p.id
WHERE sch.track_id = $1
ORDER BY sch.start_time ASC
`

type ListScheduleByTrackRow struct {
	ID              uuid.UUID          `json:"id"`
	TrackID         uuid.UUID          `json:"track_id"`
	TalkID          pgtype.UUID        `json:"talk_id"`
	StartTime       pgtype.Time        `json:"start_time"`
	EndTime         pgtype.Time        `json:"end_time"`
	Duration        pgtype.Interval    `json:"duration"`
	Room            pgtype.Text        `json:"room"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TalkTitle       pgtype.Text        `json:"talk_title"`
	SpeakerName     pgtype.Text        `json:"speaker_name"`
	SpeakerLastName pgtype.Text        `json:"speaker_last_name"`
}

func (q *Queries) ListScheduleByTrack(ctx context.Context, trackID uuid.UUID) ([]ListScheduleByTrackRow, error) {
	rows, err := q.db.Query(ctx, listScheduleByTrack, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduleByTrackRow
	for rows.Next() {
		var i ListScheduleByTrackRow
		if err := rows.Scan(
			&i.ID,
			&i.TrackID,
			&i.TalkID,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Room,
			&i.UpdatedAt,
			&i.TalkTitle,
			&i.SpeakerName,
			&i.SpeakerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleEntry = `-- name: UpdateScheduleEntry :one
UPDATE scheduler
SET 
    track_id = COALESCE($2, track_id),
    talk_id = COALESCE($3, talk_id),
    start_time = COALESCE($4, start_time),
    end_time = COALESCE($5, end_time),
    room = COALESCE($6, room),
    updated_at = NOW()
WHERE id = $1
RETURNING id, track_id, talk_id, start_time, end_time, duration, room, updated_at
`

type UpdateScheduleEntryParams struct {
	ID        uuid.UUID   `json:"id"`
	TrackID   pgtype.UUID `json:"track_id"`
	TalkID    pgtype.UUID `json:"talk_id"`
	StartTime pgtype.Time `json:"start_time"`
	EndTime   pgtype.Time `json:"end_time"`
	Room      pgtype.Text `json:"room"`
}

func (q *Queries) UpdateScheduleEntry(ctx context.Context, arg UpdateScheduleEntryParams) (Scheduler, error) {
	row := q.db.QueryRow(ctx, updateScheduleEntry,
		arg.ID,
		arg.TrackID,
		arg.TalkID,
		arg.StartTime,
		arg.EndTime,
		arg.Room,
	)
	var i Scheduler
	err := row.Scan(
		&i.ID,
		&i.TrackID,
		&i.TalkID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Room,
		&i.UpdatedAt,
	)
	return i, err
}
