// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: speakers.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSpeakersByEvent = `-- name: CountSpeakersByEvent :one
SELECT COUNT(*) 
FROM speakers s
JOIN persons p ON s.person_id = p.id
WHERE s.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($2, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountSpeakersByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountSpeakersByEvent(ctx context.Context, arg CountSpeakersByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpeakersByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpeaker = `-- name: CreateSpeaker :one
INSERT INTO speakers (
    person_id,
    event_id,
    bio,
    company,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $5
)
RETURNING id, person_id, event_id, bio, company, created_at, updated_at, created_by, updated_by
`

type CreateSpeakerParams struct {
	PersonID  uuid.UUID   `json:"person_id"`
	EventID   uuid.UUID   `json:"event_id"`
	Bio       pgtype.Text `json:"bio"`
	Company   pgtype.Text `json:"company"`
	CreatedBy uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateSpeaker(ctx context.Context, arg CreateSpeakerParams) (Speaker, error) {
	row := q.db.QueryRow(ctx, createSpeaker,
		arg.PersonID,
		arg.EventID,
		arg.Bio,
		arg.Company,
		arg.CreatedBy,
	)
	var i Speaker
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Bio,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSpeaker = `-- name: DeleteSpeaker :exec
DELETE FROM speakers
WHERE id = $1
`

func (q *Queries) DeleteSpeaker(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpeaker, id)
	return err
}

const getSpeakerByID = `-- name: GetSpeakerByID :one
SELECT 
    s.id, s.person_id, s.event_id, s.bio, s.company, s.created_at, s.updated_at, s.created_by, s.updated_by, 
    p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM speakers s
JOIN persons p ON s.person_id = p.id
WHERE s.id = $1 LIMIT 1
`

type GetSpeakerByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Bio         pgtype.Text        `json:"bio"`
	Company     pgtype.Text        `json:"company"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) GetSpeakerByID(ctx context.Context, id uuid.UUID) (GetSpeakerByIDRow, error) {
	row := q.db.QueryRow(ctx, getSpeakerByID, id)
	var i GetSpeakerByIDRow
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Bio,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubUser,
		&i.TwitterUrl,
		&i.LinkedinUrl,
	)
	return i, err
}

const getSpeakerByPersonAndEvent = `-- name: GetSpeakerByPersonAndEvent :one
SELECT id FROM speakers 
WHERE person_id = $1 AND event_id = $2
`

type GetSpeakerByPersonAndEventParams struct {
	PersonID uuid.UUID `json:"person_id"`
	EventID  uuid.UUID `json:"event_id"`
}

func (q *Queries) GetSpeakerByPersonAndEvent(ctx context.Context, arg GetSpeakerByPersonAndEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSpeakerByPersonAndEvent, arg.PersonID, arg.EventID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listSpeakersByEvent = `-- name: ListSpeakersByEvent :many
SELECT 
    s.id, s.person_id, s.event_id, s.bio, s.company, s.created_at, s.updated_at, s.created_by, s.updated_by, 
    p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM speakers s
JOIN persons p ON s.person_id = p.id
WHERE s.event_id = $1
`

type ListSpeakersByEventRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Bio         pgtype.Text        `json:"bio"`
	Company     pgtype.Text        `json:"company"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) ListSpeakersByEvent(ctx context.Context, eventID uuid.UUID) ([]ListSpeakersByEventRow, error) {
	rows, err := q.db.Query(ctx, listSpeakersByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeakersByEventRow
	for rows.Next() {
		var i ListSpeakersByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Bio,
			&i.Company,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeakersByEventPaged = `-- name: ListSpeakersByEventPaged :many
SELECT 
    s.id, s.person_id, s.event_id, s.bio, s.company, s.created_at, s.updated_at, s.created_by, s.updated_by, 
    p.first_name, p.last_name, p.email, p.avatar_url, p.github_user, p.twitter_url, p.linkedin_url
FROM speakers s
JOIN persons p ON s.person_id = p.id
WHERE s.event_id = $1 
AND (
    p.first_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.last_name ILIKE '%' || COALESCE($4, '') || '%' OR 
    p.email ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY p.first_name ASC
LIMIT $2 OFFSET $3
`

type ListSpeakersByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

type ListSpeakersByEventPagedRow struct {
	ID          uuid.UUID          `json:"id"`
	PersonID    uuid.UUID          `json:"person_id"`
	EventID     uuid.UUID          `json:"event_id"`
	Bio         pgtype.Text        `json:"bio"`
	Company     pgtype.Text        `json:"company"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	Email       pgtype.Text        `json:"email"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	GithubUser  pgtype.Text        `json:"github_user"`
	TwitterUrl  pgtype.Text        `json:"twitter_url"`
	LinkedinUrl pgtype.Text        `json:"linkedin_url"`
}

func (q *Queries) ListSpeakersByEventPaged(ctx context.Context, arg ListSpeakersByEventPagedParams) ([]ListSpeakersByEventPagedRow, error) {
	rows, err := q.db.Query(ctx, listSpeakersByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeakersByEventPagedRow
	for rows.Next() {
		var i ListSpeakersByEventPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.EventID,
			&i.Bio,
			&i.Company,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.AvatarUrl,
			&i.GithubUser,
			&i.TwitterUrl,
			&i.LinkedinUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpeaker = `-- name: UpdateSpeaker :one
UPDATE speakers
SET 
    bio = COALESCE($3, bio),
    company = COALESCE($4, company),
    updated_at = NOW(),
    updated_by = $2
WHERE id = $1
RETURNING id, person_id, event_id, bio, company, created_at, updated_at, created_by, updated_by
`

type UpdateSpeakerParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy uuid.UUID   `json:"updated_by"`
	Bio       pgtype.Text `json:"bio"`
	Company   pgtype.Text `json:"company"`
}

func (q *Queries) UpdateSpeaker(ctx context.Context, arg UpdateSpeakerParams) (Speaker, error) {
	row := q.db.QueryRow(ctx, updateSpeaker,
		arg.ID,
		arg.UpdatedBy,
		arg.Bio,
		arg.Company,
	)
	var i Speaker
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.EventID,
		&i.Bio,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
