// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sponsors.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSponsorsByEvent = `-- name: CountSponsorsByEvent :one
SELECT COUNT(*) FROM sponsors
WHERE event_id = $1
AND (
    name ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountSponsorsByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountSponsorsByEvent(ctx context.Context, arg CountSponsorsByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSponsorsByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSponsor = `-- name: CreateSponsor :one
INSERT INTO sponsors (
    event_id,
    name,
    logo_url,
    website_url,
    tier,
    order_priority,
    created_by,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7
)
RETURNING id, event_id, name, logo_url, website_url, tier, order_priority, created_at, updated_at, created_by, updated_by
`

type CreateSponsorParams struct {
	EventID       uuid.UUID   `json:"event_id"`
	Name          string      `json:"name"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	WebsiteUrl    pgtype.Text `json:"website_url"`
	Tier          pgtype.Text `json:"tier"`
	OrderPriority pgtype.Int4 `json:"order_priority"`
	CreatedBy     uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateSponsor(ctx context.Context, arg CreateSponsorParams) (Sponsor, error) {
	row := q.db.QueryRow(ctx, createSponsor,
		arg.EventID,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.Tier,
		arg.OrderPriority,
		arg.CreatedBy,
	)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.Tier,
		&i.OrderPriority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteSponsor = `-- name: DeleteSponsor :exec
DELETE FROM sponsors
WHERE id = $1
`

func (q *Queries) DeleteSponsor(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSponsor, id)
	return err
}

const getSponsorByID = `-- name: GetSponsorByID :one
SELECT id, event_id, name, logo_url, website_url, tier, order_priority, created_at, updated_at, created_by, updated_by FROM sponsors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSponsorByID(ctx context.Context, id uuid.UUID) (Sponsor, error) {
	row := q.db.QueryRow(ctx, getSponsorByID, id)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.Tier,
		&i.OrderPriority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listSponsorsByEvent = `-- name: ListSponsorsByEvent :many
SELECT id, event_id, name, logo_url, website_url, tier, order_priority, created_at, updated_at, created_by, updated_by FROM sponsors
WHERE event_id = $1
ORDER BY order_priority DESC, name ASC
`

func (q *Queries) ListSponsorsByEvent(ctx context.Context, eventID uuid.UUID) ([]Sponsor, error) {
	rows, err := q.db.Query(ctx, listSponsorsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sponsor
	for rows.Next() {
		var i Sponsor
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.Tier,
			&i.OrderPriority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSponsorsByEventPaged = `-- name: ListSponsorsByEventPaged :many
SELECT id, event_id, name, logo_url, website_url, tier, order_priority, created_at, updated_at, created_by, updated_by FROM sponsors
WHERE event_id = $1
AND (
    name ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY order_priority DESC, name ASC
LIMIT $2 OFFSET $3
`

type ListSponsorsByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) ListSponsorsByEventPaged(ctx context.Context, arg ListSponsorsByEventPagedParams) ([]Sponsor, error) {
	rows, err := q.db.Query(ctx, listSponsorsByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sponsor
	for rows.Next() {
		var i Sponsor
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.LogoUrl,
			&i.WebsiteUrl,
			&i.Tier,
			&i.OrderPriority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSponsor = `-- name: UpdateSponsor :one
UPDATE sponsors
SET 
    name = COALESCE($3, name),
    logo_url = COALESCE($4, logo_url),
    website_url = COALESCE($5, website_url),
    tier = COALESCE($6, tier),
    order_priority = COALESCE($7, order_priority),
    updated_at = NOW(),
    updated_by = $2
WHERE id = $1
RETURNING id, event_id, name, logo_url, website_url, tier, order_priority, created_at, updated_at, created_by, updated_by
`

type UpdateSponsorParams struct {
	ID            uuid.UUID   `json:"id"`
	UpdatedBy     uuid.UUID   `json:"updated_by"`
	Name          pgtype.Text `json:"name"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	WebsiteUrl    pgtype.Text `json:"website_url"`
	Tier          pgtype.Text `json:"tier"`
	OrderPriority pgtype.Int4 `json:"order_priority"`
}

func (q *Queries) UpdateSponsor(ctx context.Context, arg UpdateSponsorParams) (Sponsor, error) {
	row := q.db.QueryRow(ctx, updateSponsor,
		arg.ID,
		arg.UpdatedBy,
		arg.Name,
		arg.LogoUrl,
		arg.WebsiteUrl,
		arg.Tier,
		arg.OrderPriority,
	)
	var i Sponsor
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.LogoUrl,
		&i.WebsiteUrl,
		&i.Tier,
		&i.OrderPriority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
