// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: talks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSpeakerToTalk = `-- name: AddSpeakerToTalk :exec
INSERT INTO talk_speakers (talk_id, speaker_id, created_by)
VALUES ($1, $2, $3)
`

type AddSpeakerToTalkParams struct {
	TalkID    uuid.UUID `json:"talk_id"`
	SpeakerID uuid.UUID `json:"speaker_id"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) AddSpeakerToTalk(ctx context.Context, arg AddSpeakerToTalkParams) error {
	_, err := q.db.Exec(ctx, addSpeakerToTalk, arg.TalkID, arg.SpeakerID, arg.CreatedBy)
	return err
}

const countTalksByEvent = `-- name: CountTalksByEvent :one
SELECT COUNT(*) 
FROM talks t
WHERE t.event_id = $1 
AND (
    t.title ILIKE '%' || COALESCE($2, '') || '%' OR 
    t.description ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountTalksByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountTalksByEvent(ctx context.Context, arg CountTalksByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTalksByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTalk = `-- name: CreateTalk :one
INSERT INTO talks (
    event_id, 
    title, 
    description,
    tags,
    created_by, 
    updated_by
)
VALUES (
    $1, $2, $3, $4, $5, $5
)
RETURNING id, event_id, title, description, tags, created_at, updated_at, created_by, updated_by
`

type CreateTalkParams struct {
	EventID     uuid.UUID   `json:"event_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

func (q *Queries) CreateTalk(ctx context.Context, arg CreateTalkParams) (Talk, error) {
	row := q.db.QueryRow(ctx, createTalk,
		arg.EventID,
		arg.Title,
		arg.Description,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Talk
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTalk = `-- name: DeleteTalk :exec
DELETE FROM talks 
WHERE id = $1
`

func (q *Queries) DeleteTalk(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTalk, id)
	return err
}

const getTalkByID = `-- name: GetTalkByID :one
SELECT 
    t.id, t.event_id, t.title, t.description, t.tags, t.created_at, t.updated_at, t.created_by, t.updated_by,
    (
        SELECT json_agg(json_build_object(
            'id', s.id,
            'first_name', p.first_name,
            'last_name', p.last_name,
            'email', p.email,
            'avatar_url', p.avatar_url,
            'company', s.company,
            'bio', s.bio
        ))
        FROM talk_speakers ts
        JOIN speakers s ON ts.speaker_id = s.id
        JOIN persons p ON s.person_id = p.id
        WHERE ts.talk_id = t.id
    ) AS speakers
FROM talks t
WHERE t.id = $1 LIMIT 1
`

type GetTalkByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	Speakers    []byte             `json:"speakers"`
}

func (q *Queries) GetTalkByID(ctx context.Context, id uuid.UUID) (GetTalkByIDRow, error) {
	row := q.db.QueryRow(ctx, getTalkByID, id)
	var i GetTalkByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Speakers,
	)
	return i, err
}

const listTalksByEvent = `-- name: ListTalksByEvent :many
SELECT 
    t.id, t.event_id, t.title, t.description, t.tags, t.created_at, t.updated_at, t.created_by, t.updated_by,
    (
        SELECT json_agg(json_build_object(
            'id', s.id,
            'first_name', p.first_name,
            'last_name', p.last_name,
            'email', p.email,
            'avatar_url', p.avatar_url,
            'company', s.company,
            'bio', s.bio
        ))
        FROM talk_speakers ts
        JOIN speakers s ON ts.speaker_id = s.id
        JOIN persons p ON s.person_id = p.id
        WHERE ts.talk_id = t.id
    ) AS speakers
FROM talks t
WHERE t.event_id = $1
ORDER BY t.created_at DESC
`

type ListTalksByEventRow struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	Speakers    []byte             `json:"speakers"`
}

func (q *Queries) ListTalksByEvent(ctx context.Context, eventID uuid.UUID) ([]ListTalksByEventRow, error) {
	rows, err := q.db.Query(ctx, listTalksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTalksByEventRow
	for rows.Next() {
		var i ListTalksByEventRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Speakers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTalksByEventPaged = `-- name: ListTalksByEventPaged :many
SELECT 
    t.id, t.event_id, t.title, t.description, t.tags, t.created_at, t.updated_at, t.created_by, t.updated_by,
    (
        SELECT json_agg(json_build_object(
            'id', s.id,
            'first_name', p.first_name,
            'last_name', p.last_name,
            'email', p.email,
            'avatar_url', p.avatar_url,
            'company', s.company,
            'bio', s.bio
        ))
        FROM talk_speakers ts
        JOIN speakers s ON ts.speaker_id = s.id
        JOIN persons p ON s.person_id = p.id
        WHERE ts.talk_id = t.id
    ) AS speakers
FROM talks t
WHERE t.event_id = $1 
AND (
    t.title ILIKE '%' || COALESCE($4, '') || '%' OR 
    t.description ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTalksByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

type ListTalksByEventPagedRow struct {
	ID          uuid.UUID          `json:"id"`
	EventID     uuid.UUID          `json:"event_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	UpdatedBy   uuid.UUID          `json:"updated_by"`
	Speakers    []byte             `json:"speakers"`
}

func (q *Queries) ListTalksByEventPaged(ctx context.Context, arg ListTalksByEventPagedParams) ([]ListTalksByEventPagedRow, error) {
	rows, err := q.db.Query(ctx, listTalksByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTalksByEventPagedRow
	for rows.Next() {
		var i ListTalksByEventPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Title,
			&i.Description,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Speakers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSpeakersFromTalk = `-- name: RemoveSpeakersFromTalk :exec
DELETE FROM talk_speakers 
WHERE talk_id = $1
`

func (q *Queries) RemoveSpeakersFromTalk(ctx context.Context, talkID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeSpeakersFromTalk, talkID)
	return err
}

const updateTalk = `-- name: UpdateTalk :one
UPDATE talks SET 
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    tags = COALESCE($5, tags),
    updated_at = NOW(), 
    updated_by = $2
WHERE id = $1 
RETURNING id, event_id, title, description, tags, created_at, updated_at, created_by, updated_by
`

type UpdateTalkParams struct {
	ID          uuid.UUID   `json:"id"`
	UpdatedBy   uuid.UUID   `json:"updated_by"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Tags        []string    `json:"tags"`
}

func (q *Queries) UpdateTalk(ctx context.Context, arg UpdateTalkParams) (Talk, error) {
	row := q.db.QueryRow(ctx, updateTalk,
		arg.ID,
		arg.UpdatedBy,
		arg.Title,
		arg.Description,
		arg.Tags,
	)
	var i Talk
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Title,
		&i.Description,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
