// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tracks.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTracksByEvent = `-- name: CountTracksByEvent :one
SELECT COUNT(*) FROM tracks
WHERE event_id = $1
AND (
    name ILIKE '%' || COALESCE($2, '') || '%'
)
`

type CountTracksByEventParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) CountTracksByEvent(ctx context.Context, arg CountTracksByEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTracksByEvent, arg.EventID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (
    event_id,
    name,
    event_date
) VALUES (
    $1, $2, $3
)
RETURNING id, event_id, name, event_date, created_at, updated_at, created_by, updated_by
`

type CreateTrackParams struct {
	EventID   uuid.UUID   `json:"event_id"`
	Name      string      `json:"name"`
	EventDate pgtype.Date `json:"event_date"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, createTrack, arg.EventID, arg.Name, arg.EventDate)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM tracks
WHERE id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}

const getFullEventSchedule = `-- name: GetFullEventSchedule :many
SELECT 
    tr.id AS track_id,
    tr.name AS track_name,
    tr.event_date,
    (
        SELECT json_agg(json_build_object(
            'id', sch.id,
            'start_time', sch.start_time,
            'end_time', sch.end_time,
            'room', sch.room,
            'talk', CASE WHEN t.id IS NOT NULL THEN json_build_object(
                'id', t.id,
                'title', t.title,
                'description', t.description,
                'speakers', (
                    SELECT json_agg(json_build_object(
                        'id', s.id,
                        'first_name', p.first_name,
                        'last_name', p.last_name,
                        'avatar_url', p.avatar_url,
                        'company', s.company
                    ))
                    FROM talk_speakers ts
                    JOIN speakers s ON ts.speaker_id = s.id
                    JOIN persons p ON s.person_id = p.id
                    WHERE ts.talk_id = t.id
                )
            ) ELSE NULL END
        ) ORDER BY sch.start_time ASC)
        FROM scheduler sch
        LEFT JOIN talks t ON sch.talk_id = t.id
        WHERE sch.track_id = tr.id
    ) AS entries
FROM tracks tr
WHERE tr.event_id = $1
ORDER BY tr.event_date ASC, tr.name ASC
`

type GetFullEventScheduleRow struct {
	TrackID   uuid.UUID   `json:"track_id"`
	TrackName string      `json:"track_name"`
	EventDate pgtype.Date `json:"event_date"`
	Entries   []byte      `json:"entries"`
}

func (q *Queries) GetFullEventSchedule(ctx context.Context, eventID uuid.UUID) ([]GetFullEventScheduleRow, error) {
	rows, err := q.db.Query(ctx, getFullEventSchedule, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFullEventScheduleRow
	for rows.Next() {
		var i GetFullEventScheduleRow
		if err := rows.Scan(
			&i.TrackID,
			&i.TrackName,
			&i.EventDate,
			&i.Entries,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackByID = `-- name: GetTrackByID :one
SELECT id, event_id, name, event_date, created_at, updated_at, created_by, updated_by FROM tracks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTrackByID(ctx context.Context, id uuid.UUID) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByID, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const listTracksByEvent = `-- name: ListTracksByEvent :many
SELECT id, event_id, name, event_date, created_at, updated_at, created_by, updated_by FROM tracks
WHERE event_id = $1
ORDER BY event_date ASC, name ASC
`

func (q *Queries) ListTracksByEvent(ctx context.Context, eventID uuid.UUID) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracksByEventPaged = `-- name: ListTracksByEventPaged :many
SELECT id, event_id, name, event_date, created_at, updated_at, created_by, updated_by FROM tracks
WHERE event_id = $1
AND (
    name ILIKE '%' || COALESCE($4, '') || '%'
)
ORDER BY event_date ASC, name ASC
LIMIT $2 OFFSET $3
`

type ListTracksByEventPagedParams struct {
	EventID uuid.UUID   `json:"event_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
	Search  pgtype.Text `json:"search"`
}

func (q *Queries) ListTracksByEventPaged(ctx context.Context, arg ListTracksByEventPagedParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, listTracksByEventPaged,
		arg.EventID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.EventDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrack = `-- name: UpdateTrack :one
UPDATE tracks
SET 
    name = COALESCE($2, name),
    event_date = COALESCE($3, event_date)
WHERE id = $1
RETURNING id, event_id, name, event_date, created_at, updated_at, created_by, updated_by
`

type UpdateTrackParams struct {
	ID        uuid.UUID   `json:"id"`
	Name      pgtype.Text `json:"name"`
	EventDate pgtype.Date `json:"event_date"`
}

func (q *Queries) UpdateTrack(ctx context.Context, arg UpdateTrackParams) (Track, error) {
	row := q.db.QueryRow(ctx, updateTrack, arg.ID, arg.Name, arg.EventDate)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}
